---
title: "INFSCI 2595 Final Project"
subtitle: "Part 2D4, Regression-Best Model"
author: "Radhika Purohit"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages}
library(tidyverse)
theme_set(theme_linedraw())
library(tidymodels)
tidymodels_prefer()
```

----

## Regression: Best Model

Compare and choose the best model for the regression task from:  

- Best baseline linear model
- Best regularized Elastic Net model
- Best advanced model

**Read in the 3 best models from part 2D1 - 2D3.**  

```{r}
mod_2D_lm_best_resample <- readr::read_rds("mod_2D_lm_best_resample.rds")
mod_2D_enet_best_resample <- readr::read_rds("mod_2D_enet_best_resample.rds")
mod_2D_adv_best_resample <- readr::read_rds("mod_2D_adv_best_resample.rds")
my_models <- mget(ls(pattern = "^mod_2D.+_resample"))
```

**Compare model parameters.**  

```{r metrics}
my_models %>%
  map_dfr(collect_metrics, .id="model") %>%
  ggplot(aes(x=model, color=model)) +
  geom_pointrange(
    aes(y = mean, ymin = mean - std_err, ymax = mean + std_err, group = model)) +
  facet_wrap(~ .metric, scales = "free_y") +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
```

- From above results, the best model from the (XGBoost, red) has the best performance. 
- Thus the **best model for regression task is determined to be the XGBoost**. 

----



